

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabnb.frontend;

import java.awt.Container;
import java.awt.Point;
import java.util.ArrayList;
import javabnb.backend.*;
import javabnb.frontend.EditarAnfitrion;
import javabnb.frontend.EditarCliente;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEJANDRO
 */
public class BuscarInmuebles extends javax.swing.JFrame {

    Persona persona;
    /**
     * Creates new form MenuPrincipal
     * 
     * @param inicioSesion
     */
    public BuscarInmuebles( Point localizacion, Persona persona) {
        this.setLocation(localizacion);
        this.persona = persona;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        foto1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        tipo1 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        media1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        FiltroPrecio = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        foto2 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        tipo2 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        media2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        foto3 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        tipo3 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        media3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        foto4 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        tipo4 = new javax.swing.JLabel();
        precio4 = new javax.swing.JLabel();
        media4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        filtroReseñas = new javax.swing.JRadioButton();
        botonSiguiente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        botonPerfil = new javax.swing.JMenuItem();

        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanelBusqueda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 70, -1, -1));

        jButton1.setText("jButton1");
        jPanelBusqueda.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 174, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBnB");
        setMinimumSize(new java.awt.Dimension(900, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto1.setText("iMAGENN");
        jPanel4.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo1.setText("TITULO");
        jPanel4.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));

        tipo1.setText("TIPO");
        jPanel4.add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, -1));

        precio1.setText("€€€€");
        jPanel4.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));

        media1.setText("Media");
        jPanel4.add(media1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 690, 130));

        jTextField1.setText("BUSCAR POR CIUDAD");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 421, -1));

        FiltroPrecio.setText("POR PRECIO");
        FiltroPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(FiltroPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 730, 75, -1));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 75, -1));

        botonAtras.setText("Anterior");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto2.setText("iMAGENN");
        jPanel5.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo2.setText("titulo2");
        jPanel5.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));

        tipo2.setText("TIPO");
        jPanel5.add(tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, -1));

        precio2.setText("€€€€");
        jPanel5.add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));

        media2.setText("Media");
        jPanel5.add(media2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 690, 130));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto3.setText("iMAGENN");
        jPanel6.add(foto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo3.setText("TITULO");
        jPanel6.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));

        tipo3.setText("TIPO");
        jPanel6.add(tipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, -1));

        precio3.setText("€€€€");
        jPanel6.add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));

        media3.setText("Media");
        jPanel6.add(media3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 690, 130));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto4.setText("iMAGENN");
        jPanel7.add(foto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo4.setText("TITULO");
        jPanel7.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));

        tipo4.setText("TIPO");
        jPanel7.add(tipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, -1));

        precio4.setText("€€€€");
        jPanel7.add(precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));

        media4.setText("Media");
        jPanel7.add(media4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 690, 130));

        jLabel2.setText("FILTROS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jCheckBox1.setText("Casa");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jCheckBox2.setText("Apartamento");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        filtroReseñas.setText("POR RESEÑAS");
        filtroReseñas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroReseñasActionPerformed(evt);
            }
        });
        getContentPane().add(filtroReseñas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, -1, -1));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 73));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 73));

        jMenu1.setText("Busqueda");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu1.setMinimumSize(new java.awt.Dimension(120, 22));

        jMenuItem3.setText("Buscar inmuebles");
        jMenuItem3.setToolTipText("");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reseñas");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu2.setMinimumSize(new java.awt.Dimension(120, 22));

        jMenuItem4.setText("Escribir reseña");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reservas");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu3.setMinimumSize(new java.awt.Dimension(120, 22));

        jMenuItem2.setText("Consultar reservas");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Perfil");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu4.setMinimumSize(new java.awt.Dimension(120, 45));

        botonPerfil.setText("Modificar datos");
        botonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPerfilActionPerformed(evt);
            }
        });
        jMenu4.add(botonPerfil);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPerfilActionPerformed
        if (persona instanceof Anfitrion) {
        EditarAnfitrion editaranfitrion = new EditarAnfitrion(this.getLocation(),persona);
        this.dispose();}
        else {
        EditarCliente editarcliente = new EditarCliente(this.getLocation(),persona);
               this.dispose();}  
                
        
    }//GEN-LAST:event_botonPerfilActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void filtroReseñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroReseñasActionPerformed
    inmuebles = GestorInmueble.getInmuebles();
         ArrayList<Inmueble> inmuebles = GestorInmueble.getInmueblesPorCalificacion();
        }
    }//GEN-LAST:event_filtroReseñasActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        if (pagAct > 0){ pagAct++;}
        
        titulo1.setText(inmuebles.get(pagAct*4).getTitulo());
        titulo2.setText(inmuebles.get(1+(pagAct*4)).getTitulo());
        titulo3.setText(inmuebles.get(2+(pagAct*4)).getTitulo());
        titulo4.setText(inmuebles.get(3+(pagAct*4)).getTitulo());
        
        precio1.setText(Double.toString(inmuebles.get(pagAct*4).getPrecioNoche()));
        precio2.setText(Double.toString(inmuebles.get(1+pagAct*4).getPrecioNoche()));
        precio3.setText(Double.toString(inmuebles.get(2+pagAct*4).getPrecioNoche()));
        precio4.setText(Double.toString(inmuebles.get(3+pagAct*4).getPrecioNoche()));

        media1.setText(Double.toString(inmuebles.get(pagAct*4).getCalificacion()));
        media2.setText(Double.toString(inmuebles.get(1+pagAct*4).getCalificacion()));
        media3.setText(Double.toString(inmuebles.get(2+pagAct*4).getCalificacion()));
        media4.setText(Double.toString(inmuebles.get(3+pagAct*4).getCalificacion()));
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        if (pagAct < numPag){ pagAct--;}

        titulo1.setText(inmuebles.get(pagAct*4).getTitulo());
        titulo2.setText(inmuebles.get(1+(pagAct*4)).getTitulo());
        titulo3.setText(inmuebles.get(2+(pagAct*4)).getTitulo());
        titulo4.setText(inmuebles.get(3+(pagAct*4)).getTitulo());
        
        precio1.setText(Double.toString(inmuebles.get(pagAct*4).getPrecioNoche()));
        precio2.setText(Double.toString(inmuebles.get(1+pagAct*4).getPrecioNoche()));
        precio3.setText(Double.toString(inmuebles.get(2+pagAct*4).getPrecioNoche()));
        precio4.setText(Double.toString(inmuebles.get(3+pagAct*4).getPrecioNoche()));

        media1.setText(Double.toString(inmuebles.get(pagAct*4).getCalificacion()));
        media2.setText(Double.toString(inmuebles.get(1+pagAct*4).getCalificacion()));
        media3.setText(Double.toString(inmuebles.get(2+pagAct*4).getCalificacion()));
        media4.setText(Double.toString(inmuebles.get(3+pagAct*4).getCalificacion()));
    }//GEN-LAST:event_botonSiguienteActionPerformed
    ArrayList<Inmueble> inmuebles = GestorInmueble.getInmuebles();
    int pagAct = 0; 
    int numPag = (int) Math.ceil(inmuebles.size()/4);
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FiltroPrecio;
    private javax.swing.JButton botonAtras;
    private javax.swing.JMenuItem botonPerfil;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private java.awt.Canvas canvas1;
    private javax.swing.JRadioButton filtroReseñas;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel foto4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel media1;
    private javax.swing.JLabel media2;
    private javax.swing.JLabel media3;
    private javax.swing.JLabel media4;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precio4;
    private javax.swing.JLabel tipo1;
    private javax.swing.JLabel tipo2;
    private javax.swing.JLabel tipo3;
    private javax.swing.JLabel tipo4;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
