/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabnb.frontend;

import java.awt.Point;
import javabnb.backend.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sco23
 */
public class CambiarContraseña extends javax.swing.JFrame {


    /**
     * Creates new form CambiarContraseña
     * @param localizacion
     * @param persona
     */
    public CambiarContraseña(Point localizacion, Persona persona) {
       
        this.setLocation(localizacion );
        this.persona = persona;
        initComponents();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonClave1 = new javax.swing.JTextField();
        botonClave2 = new javax.swing.JTextField();
        contraseñaActual = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaBnB");
        setResizable(false);

        jLabel1.setText("Contraseña Actual:");

        jLabel2.setText("Nueva contraseña:");

        jLabel3.setText("Repita la nueva contraseña:");

        contraseñaActual.setText("jPasswordField1");
        contraseñaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActualActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("CAMBIAR CONTRASEÑA");

        botonConfirmar.setText("Confirmar");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonClave2)
                            .addComponent(botonClave1)
                            .addComponent(contraseñaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(contraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(botonClave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(botonClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActualActionPerformed

    }//GEN-LAST:event_contraseñaActualActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
               String password = new String(contraseñaActual.getPassword());
        if (password.equals(persona.getClave())){
       ContraseñaCorrecta = true; 
    }
    else {
       ContraseñaCorrecta = false;
    }
        
        if (ContraseñaCorrecta && botonClave1.getText().equals(botonClave2.getText()) && !botonClave1.getText().equals("")){
        persona.setClave(botonClave1.getText());
        this.dispose();  
        }
         if (!ContraseñaCorrecta && botonClave1.getText().equals(botonClave2.getText())){
          JOptionPane.showMessageDialog(this,"la contraseña anterior es incorrecta","error de contraseña",JOptionPane.WARNING_MESSAGE);
          contraseñaActual.setText("");
         }
          if (ContraseñaCorrecta && !botonClave1.getText().equals(botonClave2.getText())){
          JOptionPane.showMessageDialog(this,"Las contraseñas no coinciden","error de contraseña",JOptionPane.WARNING_MESSAGE);
          botonClave1.setText("");
          botonClave2.setText("");
          }
           if (!ContraseñaCorrecta && !botonClave1.getText().equals(botonClave2.getText())){
          JOptionPane.showMessageDialog(this,"Las contraseñas no coinciden","error de contraseña",JOptionPane.WARNING_MESSAGE);
          botonClave1.setText("");
          botonClave2.setText("");
          contraseñaActual.setText("");
          JOptionPane.showMessageDialog(this,"Todos los datos introducidos son incorrectos","error de contraseña",JOptionPane.WARNING_MESSAGE);
           }
     
      
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private Persona persona;
    boolean ContraseñaCorrecta = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField botonClave1;
    private javax.swing.JTextField botonClave2;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JPasswordField contraseñaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
