/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javabnb.frontend;

/**
 *
 * @author sco23
 */
public class MenuPrincipalAnfitrion extends javax.swing.JDialog {

    /**
     * Creates new form MenuPrincipalCliente
     */
    public MenuPrincipalAnfitrion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    MenuPrincipalAnfitrion() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonAñadirInm = new javax.swing.JButton();
        botonReseñas = new javax.swing.JButton();
        botonReservas = new javax.swing.JButton();
        botonDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoJavaBnB-removebg.png"))); // NOI18N

        jToolBar1.setRollover(true);

        botonAñadirInm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonAñadirInm.setText("Añadir inmueble");
        botonAñadirInm.setToolTipText("");
        botonAñadirInm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        botonAñadirInm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAñadirInm.setMaximumSize(new java.awt.Dimension(100, 100));
        botonAñadirInm.setName(""); // NOI18N
        botonAñadirInm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAñadirInm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirInmActionPerformed(evt);
            }
        });
        jToolBar1.add(botonAñadirInm);

        botonReseñas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonReseñas.setText("Reseñas");
        botonReseñas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        botonReseñas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonReseñas.setMaximumSize(new java.awt.Dimension(100, 100));
        botonReseñas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonReseñas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReseñasActionPerformed(evt);
            }
        });
        jToolBar1.add(botonReseñas);

        botonReservas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonReservas.setText("Reservas");
        botonReservas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        botonReservas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonReservas.setMaximumSize(new java.awt.Dimension(100, 100));
        botonReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservasActionPerformed(evt);
            }
        });
        jToolBar1.add(botonReservas);

        botonDatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonDatos.setText("Datos");
        botonDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        botonDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDatos.setMaximumSize(new java.awt.Dimension(100, 100));
        botonDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDatosActionPerformed(evt);
            }
        });
        jToolBar1.add(botonDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirInmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirInmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAñadirInmActionPerformed

    private void botonReseñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReseñasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReseñasActionPerformed

    private void botonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDatosActionPerformed

    private void botonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipalAnfitrion dialog = new MenuPrincipalAnfitrion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirInm;
    private javax.swing.JButton botonDatos;
    private javax.swing.JButton botonReservas;
    private javax.swing.JButton botonReseñas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
