

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabnb.frontend;

import java.awt.Point;
import java.util.ArrayList;
import javabnb.backend.*;
import javabnb.frontend.EditarAnfitrion;
import javabnb.frontend.EditarCliente;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEJANDRO
 */
public class MenuAdministrador extends javax.swing.JFrame {

    private Persona persona;
    /**
     * Creates new form MenuPrincipal
     * 
     * @param localizacion
     * @param persona
     */
    public MenuAdministrador( Point localizacion) {
        this.setLocation(localizacion);
        this.persona = persona;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inmuebles = new javax.swing.JMenu();
        botonInmuebles = new javax.swing.JMenuItem();
        Usuarios = new javax.swing.JMenu();
        mostrarUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        botonReservas = new javax.swing.JMenuItem();

        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanelBusqueda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 70, -1, -1));

        jButton1.setText("jButton1");
        jPanelBusqueda.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 174, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBnB");
        setMinimumSize(new java.awt.Dimension(900, 720));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoJavaBnB-PNGx2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 73));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 73));

        Inmuebles.setText("Inmuebles");
        Inmuebles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inmuebles.setMaximumSize(new java.awt.Dimension(120, 32767));
        Inmuebles.setMinimumSize(new java.awt.Dimension(120, 22));

        botonInmuebles.setText("Mostar Inmuebles");
        botonInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInmueblesActionPerformed(evt);
            }
        });
        Inmuebles.add(botonInmuebles);

        jMenuBar1.add(Inmuebles);

        Usuarios.setText("Usuarios");
        Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Usuarios.setMaximumSize(new java.awt.Dimension(120, 32767));
        Usuarios.setMinimumSize(new java.awt.Dimension(120, 22));

        mostrarUsuarios.setText("Mostrar usuarios");
        mostrarUsuarios.setToolTipText("");
        mostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarUsuariosActionPerformed(evt);
            }
        });
        Usuarios.add(mostrarUsuarios);

        jMenuBar1.add(Usuarios);

        jMenu3.setText("Reservas");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu3.setMinimumSize(new java.awt.Dimension(120, 22));

        botonReservas.setText("Mostrar reservas");
        botonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservasActionPerformed(evt);
            }
        });
        jMenu3.add(botonReservas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarUsuariosActionPerformed
        VerUsuariosAdministrador userAdmin = new VerUsuariosAdministrador(this.getLocation());
        userAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mostrarUsuariosActionPerformed

    private void botonInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInmueblesActionPerformed
       
        BuscarInmueblesAdministrador menuAdmin = new BuscarInmueblesAdministrador(this.getLocation());
        menuAdmin.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_botonInmueblesActionPerformed

    private void botonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservasActionPerformed
        ConsultarReservasAdministrador menuAdmin = new ConsultarReservasAdministrador(this.getLocation());
        menuAdmin.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_botonReservasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this,"Estas seguro de cerrar","Cierre programa",JOptionPane.WARNING_MESSAGE);
        GestorInmueble.guardarDatosInmuebles();
        System.out.println("Guardando datos de inmuebles");
        GestorInmueble.guardarDatosPersonas();
        System.out.println("Guardando datos de personas");
        GestorInmueble.guardarDatosReservas();
        System.out.println("Guardando datos de reservas");
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Inmuebles;
    private javax.swing.JMenu Usuarios;
    private javax.swing.JMenuItem botonInmuebles;
    private javax.swing.JMenuItem botonReservas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JMenuItem mostrarUsuarios;
    // End of variables declaration//GEN-END:variables
}
