

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabnb.frontend;

import java.awt.Container;
import java.awt.Image;
import java.awt.Point;
import java.util.ArrayList;
import javabnb.backend.*;
import javabnb.frontend.EditarAnfitrion;
import javabnb.frontend.EditarCliente;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEJANDRO
 */
public class ModificarInmueble extends javax.swing.JFrame {

    private Persona persona;
    private Anfitrion anfitrion;
    /**
     * Creates new form MenuPrincipal
     * 
     * @param localizacion
     * @param persona
     */
    public ModificarInmueble( Point localizacion, Persona persona) {
        this.setLocation(localizacion);
        this.persona = persona;
        this.anfitrion = (Anfitrion) persona;
        initComponents();
        this.setVisible(true);
        if (persona instanceof ClienteParticular) {
            jMenu1.setText("Busqueda");
            buscarGestionarInmuebles.setText("Busqueda Inmuebles");
        }
        else {
            jMenu1.setText("Añadir");
            buscarGestionarInmuebles.setText("Añadir inmueble");
        }

        if (persona instanceof ClienteParticular) {
            jMenu2.setText("Reseñas");
            btnReseñaModInm.setText("Escribir Reseñas");
        }
        else {
            jMenu2.setText("Gestionar");
            btnReseñaModInm.setText("Modificar inmueble");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        foto1 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        media1 = new javax.swing.JLabel();
        AmpliarInmueble1 = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        foto2 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        media2 = new javax.swing.JLabel();
        inmueble2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        foto3 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        media3 = new javax.swing.JLabel();
        inmueble3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        foto4 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        precio4 = new javax.swing.JLabel();
        media4 = new javax.swing.JLabel();
        inmueble4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        filtroCasa = new javax.swing.JCheckBox();
        filtroApartamento = new javax.swing.JCheckBox();
        botonReseña = new javax.swing.JRadioButton();
        botonSiguiente = new javax.swing.JButton();
        botonPorPrecio = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buscarGestionarInmuebles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnReseñaModInm = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnReservas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        botonPerfil = new javax.swing.JMenuItem();

        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanelBusqueda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 70, -1, -1));

        jButton1.setText("jButton1");
        jPanelBusqueda.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 174, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBnB");
        setMinimumSize(new java.awt.Dimension(1100, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));
        jPanel4.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));
        jPanel4.add(media1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        AmpliarInmueble1.setText("Modificar");
        AmpliarInmueble1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmpliarInmueble1ActionPerformed(evt);
            }
        });
        jPanel4.add(AmpliarInmueble1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 690, 130));

        botonAtras.setText("Anterior");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel5.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));
        jPanel5.add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));
        jPanel5.add(media2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        inmueble2.setText("Modificar");
        inmueble2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inmueble2ActionPerformed(evt);
            }
        });
        jPanel5.add(inmueble2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 690, 130));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(foto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));
        jPanel6.add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));
        jPanel6.add(media3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        inmueble3.setText("Modificar");
        inmueble3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inmueble3ActionPerformed(evt);
            }
        });
        jPanel6.add(inmueble3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 690, 130));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(foto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        titulo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel7.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 40));
        jPanel7.add(precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, -1));
        jPanel7.add(media4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        inmueble4.setText("Modificar");
        inmueble4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inmueble4ActionPerformed(evt);
            }
        });
        jPanel7.add(inmueble4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 690, 130));

        jLabel2.setText("FILTROS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        filtroCasa.setText("Casa");
        filtroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroCasaActionPerformed(evt);
            }
        });
        getContentPane().add(filtroCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        filtroApartamento.setText("Apartamento");
        filtroApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroApartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(filtroApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        botonReseña.setText("POR RESEÑAS");
        botonReseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReseñaActionPerformed(evt);
            }
        });
        getContentPane().add(botonReseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        botonPorPrecio.setText("POR PRECIO");
        botonPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(botonPorPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 73));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 73));

        jMenu1.setText("Busqueda");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu1.setMinimumSize(new java.awt.Dimension(120, 22));

        buscarGestionarInmuebles.setText("Buscar inmuebles");
        buscarGestionarInmuebles.setToolTipText("");
        buscarGestionarInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGestionarInmueblesActionPerformed(evt);
            }
        });
        jMenu1.add(buscarGestionarInmuebles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reseñas");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu2.setMinimumSize(new java.awt.Dimension(120, 22));

        btnReseñaModInm.setText("Escribir reseña");
        btnReseñaModInm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReseñaModInmActionPerformed(evt);
            }
        });
        jMenu2.add(btnReseñaModInm);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reservas");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu3.setMinimumSize(new java.awt.Dimension(120, 22));

        btnReservas.setText("Consultar reservas");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });
        jMenu3.add(btnReservas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Perfil");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu4.setMinimumSize(new java.awt.Dimension(120, 45));

        botonPerfil.setText("Modificar datos");
        botonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPerfilActionPerformed(evt);
            }
        });
        jMenu4.add(botonPerfil);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPerfilActionPerformed
        if (persona instanceof Anfitrion) {
            EditarAnfitrion editaranfitrion = new EditarAnfitrion(this.getLocation(),persona);
            this.dispose();
        }
        else {
            EditarCliente editarcliente = new EditarCliente(this.getLocation(),persona);
            this.dispose();
        }  
    }//GEN-LAST:event_botonPerfilActionPerformed

    private void buscarGestionarInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarGestionarInmueblesActionPerformed
        if (persona instanceof ClienteParticular) {
            BuscarInmuebles busquedaInm = new BuscarInmuebles(this.getLocation(),persona);
            this.dispose();
        } else {
            CrearInmueble crearInmueble = new CrearInmueble(this.getLocation(),persona);
            this.dispose();
        }
    }//GEN-LAST:event_buscarGestionarInmueblesActionPerformed

    private void btnReseñaModInmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReseñaModInmActionPerformed
        if (persona instanceof Anfitrion) {
            ModificarInmueble modInmueble = new ModificarInmueble(this.getLocation(),persona);
            this.dispose();
        }
        else {
            AñadirReseña añadirReseña = new AñadirReseña(this.getLocation(),persona);
            this.dispose();
        }  
    }//GEN-LAST:event_btnReseñaModInmActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        ConsultarReservasAnfitrion consultarReservas = new ConsultarReservasAnfitrion(this.getLocation(),persona);
        this.dispose();
    }//GEN-LAST:event_btnReservasActionPerformed

    private void AmpliarInmueble1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmpliarInmueble1ActionPerformed
        Inmueble inmueble1 = listaInmuebles.get(pagAct*4);

        if (!titulo1.getText().equals("")){
            if (botonPorPrecio.isSelected()) {GestorInmueble.getInmueblesPorPrecio();}
            if (botonReseña.isSelected()) {GestorInmueble.getInmueblesPorCalificacion();}
            if (filtroCasa.isSelected()) {GestorInmueble.getInmueblesPorTipo("CASA");}
            if (filtroApartamento.isSelected()) {GestorInmueble.getInmueblesPorTipo("APARTAMENTO");}
            MenuModificar modInmueble = new MenuModificar(this.getLocation(),persona,inmueble1);
            this.dispose();
        }
    }//GEN-LAST:event_AmpliarInmueble1ActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        if (pagAct >0) {pagAct--;}
        titulo1.setText("");
        precio1.setText("");
        media1.setText("");
        foto1.setIcon(null);

        titulo2.setText("");
        precio2.setText("");
        media2.setText("");
        foto2.setIcon(null);

        titulo3.setText("");
        precio3.setText("");
        media3.setText("");
        foto3.setIcon(null);

        titulo4.setText("");
        precio4.setText("");
        media4.setText("");
        foto4.setIcon(null);

        if (startIndex < listaInmuebles.size()) {
            Inmueble inmueble1 = listaInmuebles.get(startIndex);
            Image imagen1 = inmueble1.getFotos().get(0).getImage();

            titulo1.setText(inmueble1.getTitulo());
            precio1.setText(Double.toString(inmueble1.getPrecioNoche()));
            media1.setText(Double.toString(inmueble1.getCalificacion()));
            foto1.setIcon(inmueble1.getFotos().get(0)); // Asegúrate de manejar bien las fotos
        }
        if (startIndex + 1 < listaInmuebles.size()) {
            Inmueble inmueble2 = listaInmuebles.get(startIndex + 1);
            titulo2.setText(inmueble2.getTitulo());
            precio2.setText(Double.toString(inmueble2.getPrecioNoche()));
            media2.setText(Double.toString(inmueble2.getCalificacion()));
            foto2.setIcon(inmueble2.getFotos().get(0));
        }
        if (startIndex + 2 < listaInmuebles.size()) {
            Inmueble inmueble3 = listaInmuebles.get(startIndex + 2);
            titulo3.setText(inmueble3.getTitulo());
            precio3.setText(Double.toString(inmueble3.getPrecioNoche()));
            media3.setText(Double.toString(inmueble3.getCalificacion()));
            foto3.setIcon(inmueble3.getFotos().get(0));
        }
        if (startIndex + 3 < listaInmuebles.size()) {
            Inmueble inmueble4 = listaInmuebles.get(startIndex + 3);
            titulo4.setText(inmueble4.getTitulo());
            precio4.setText(Double.toString(inmueble4.getPrecioNoche()));
            media4.setText(Double.toString(inmueble4.getCalificacion()));
            foto4.setIcon(inmueble4.getFotos().get(0));
        }

    }//GEN-LAST:event_botonAtrasActionPerformed

    private void inmueble2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inmueble2ActionPerformed
        Inmueble inmueble2 = listaInmuebles.get(1+pagAct*4);

        if (!titulo2.getText().equals("")){
            if (botonPorPrecio.isSelected()) {GestorInmueble.getInmueblesPorPrecio();}
            if (botonReseña.isSelected()) {GestorInmueble.getInmueblesPorCalificacion();}
            if (filtroCasa.isSelected()) {GestorInmueble.getInmueblesPorTipo("CASA");}
            if (filtroApartamento.isSelected()) {GestorInmueble.getInmueblesPorTipo("APARTAMENTO");}
            MenuModificar modInmueble = new MenuModificar(this.getLocation(),persona,inmueble2);
            this.dispose();
        }
    }//GEN-LAST:event_inmueble2ActionPerformed

    private void inmueble3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inmueble3ActionPerformed
        Inmueble inmueble3 = listaInmuebles.get(2+pagAct*4);
        if (!titulo3.getText().equals("")){
            if (botonPorPrecio.isSelected()) {GestorInmueble.getInmueblesPorPrecio();}
            if (botonReseña.isSelected()) {GestorInmueble.getInmueblesPorCalificacion();}
            if (filtroCasa.isSelected()) {GestorInmueble.getInmueblesPorTipo("CASA");}
            if (filtroApartamento.isSelected()) {GestorInmueble.getInmueblesPorTipo("APARTAMENTO");}
            MenuModificar modInmueble = new MenuModificar(this.getLocation(),persona,inmueble3);
            this.dispose();
        }
    }//GEN-LAST:event_inmueble3ActionPerformed

    private void inmueble4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inmueble4ActionPerformed
        Inmueble inmueble4 = listaInmuebles.get(3+pagAct*4);
        if (!titulo4.getText().equals("")){
            if (botonPorPrecio.isSelected()) {GestorInmueble.getInmueblesPorPrecio();}
            if (botonReseña.isSelected()) {GestorInmueble.getInmueblesPorCalificacion();}
            if (filtroCasa.isSelected()) {GestorInmueble.getInmueblesPorTipo("CASA");}
            if (filtroApartamento.isSelected()) {GestorInmueble.getInmueblesPorTipo("APARTAMENTO");}
            MenuModificar modInmueble = new MenuModificar(this.getLocation(),persona,inmueble4);
            this.dispose();
        }
    }//GEN-LAST:event_inmueble4ActionPerformed

    private void filtroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroCasaActionPerformed
        listaInmuebles = listaInmuebles2;
        botonReseña.setSelected(false);
        botonPorPrecio.setSelected(false);
        filtroApartamento.setSelected(false);
        ArrayList<Inmueble> listaInmuebles = GestorInmueble.getInmueblesPorTipo("CASA");
        pagAct = 0;
        titulo1.setText("");
        precio1.setText("");
        media1.setText("");
        foto1.setIcon(null);

        titulo2.setText("");
        precio2.setText("");
        media2.setText("");
        foto2.setIcon(null);

        titulo3.setText("");
        precio3.setText("");
        media3.setText("");
        foto3.setIcon(null);

        titulo4.setText("");
        precio4.setText("");
        media4.setText("");
        foto4.setIcon(null);

        if (startIndex < listaInmuebles.size()) {
            Inmueble inmueble1 = listaInmuebles.get(startIndex);
            Image imagen1 = inmueble1.getFotos().get(0).getImage();
            titulo1.setText(inmueble1.getTitulo());
            precio1.setText(Double.toString(inmueble1.getPrecioNoche()));
            media1.setText(Double.toString(inmueble1.getCalificacion()));
            foto1.setIcon(inmueble1.getFotos().get(0)); // Asegúrate de manejar bien las fotos
        }
        if (startIndex + 1 < listaInmuebles.size()) {
            Inmueble inmueble2 = listaInmuebles.get(startIndex + 1);
            titulo2.setText(inmueble2.getTitulo());
            precio2.setText(Double.toString(inmueble2.getPrecioNoche()));
            media2.setText(Double.toString(inmueble2.getCalificacion()));
            foto2.setIcon(inmueble2.getFotos().get(0));
        }
        if (startIndex + 2 < listaInmuebles.size()) {
            Inmueble inmueble3 = listaInmuebles.get(startIndex + 2);
            titulo3.setText(inmueble3.getTitulo());
            precio3.setText(Double.toString(inmueble3.getPrecioNoche()));
            media3.setText(Double.toString(inmueble3.getCalificacion()));
            foto3.setIcon(inmueble3.getFotos().get(0));
        }
        if (startIndex + 3 < listaInmuebles.size()) {
            Inmueble inmueble4 = listaInmuebles.get(startIndex + 3);
            titulo4.setText(inmueble4.getTitulo());
            precio4.setText(Double.toString(inmueble4.getPrecioNoche()));
            media4.setText(Double.toString(inmueble4.getCalificacion()));
            foto4.setIcon(inmueble4.getFotos().get(0));
        }
    }//GEN-LAST:event_filtroCasaActionPerformed

    private void filtroApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroApartamentoActionPerformed
        listaInmuebles = listaInmuebles2;
        botonReseña.setSelected(false);
        botonPorPrecio.setSelected(false);
        filtroCasa.setSelected(false);
        ArrayList<Inmueble> listaInmuebles = GestorInmueble.getInmueblesPorTipo("APARTAMENTO");
        pagAct = 0;
        titulo1.setText("");
        precio1.setText("");
        media1.setText("");
        foto1.setIcon(null);

        titulo2.setText("");
        precio2.setText("");
        media2.setText("");
        foto2.setIcon(null);

        titulo3.setText("");
        precio3.setText("");
        media3.setText("");
        foto3.setIcon(null);

        titulo4.setText("");
        precio4.setText("");
        media4.setText("");
        foto4.setIcon(null);

        if (startIndex < listaInmuebles.size()) {
            Inmueble inmueble1 = listaInmuebles.get(startIndex);
            /*Image imagen1 = inmueble1.getFotos().get(0).getImage(); // transform it
            Image newimg1 = imagen1.getScaledInstance(90, 10,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            this.imagen1 = new ImageIcon(newimg1);*/
            titulo1.setText(inmueble1.getTitulo());
            precio1.setText(Double.toString(inmueble1.getPrecioNoche()));
            media1.setText(Double.toString(inmueble1.getCalificacion()));
            foto1.setIcon((Icon) imagen1); // Asegúrate de manejar bien las fotos
        }
        if (startIndex + 1 < listaInmuebles.size()) {
            Inmueble inmueble2 = listaInmuebles.get(startIndex + 1);
            titulo2.setText(inmueble2.getTitulo());
            precio2.setText(Double.toString(inmueble2.getPrecioNoche()));
            media2.setText(Double.toString(inmueble2.getCalificacion()));
            foto2.setIcon(inmueble2.getFotos().get(0));
        }
        if (startIndex + 2 < listaInmuebles.size()) {
            Inmueble inmueble3 = listaInmuebles.get(startIndex + 2);
            titulo3.setText(inmueble3.getTitulo());
            precio3.setText(Double.toString(inmueble3.getPrecioNoche()));
            media3.setText(Double.toString(inmueble3.getCalificacion()));
            foto3.setIcon(inmueble3.getFotos().get(0));
        }
        if (startIndex + 3 < listaInmuebles.size()) {
            Inmueble inmueble4 = listaInmuebles.get(startIndex + 3);
            titulo4.setText(inmueble4.getTitulo());
            precio4.setText(Double.toString(inmueble4.getPrecioNoche()));
            media4.setText(Double.toString(inmueble4.getCalificacion()));
            foto4.setIcon(inmueble4.getFotos().get(0));
        }
    }//GEN-LAST:event_filtroApartamentoActionPerformed

    private void botonReseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReseñaActionPerformed
        filtroCasa.setSelected(false);
        filtroApartamento.setSelected(false);
        botonPorPrecio.setSelected(false);
        listaInmuebles = listaInmuebles2;
        ArrayList<Inmueble> listaInmuebles = GestorInmueble.getInmueblesPorCalificacion();
        pagAct = 0;
        titulo1.setText("");
        precio1.setText("");
        media1.setText("");
        foto1.setIcon(null);

        titulo2.setText("");
        precio2.setText("");
        media2.setText("");
        foto2.setIcon(null);

        titulo3.setText("");
        precio3.setText("");
        media3.setText("");
        foto3.setIcon(null);

        titulo4.setText("");
        precio4.setText("");
        media4.setText("");
        foto4.setIcon(null);

        if (startIndex < listaInmuebles.size()) {

            Inmueble inmueble1 = listaInmuebles.get(startIndex);
            Image imagen1 = inmueble1.getFotos().get(0).getImage();
            titulo1.setText(inmueble1.getTitulo());
            precio1.setText(Double.toString(inmueble1.getPrecioNoche()));
            media1.setText(Double.toString(inmueble1.getCalificacion()));
            foto1.setIcon(inmueble1.getFotos().get(0)); // Asegúrate de manejar bien las fotos
        }
        if (startIndex + 1 < listaInmuebles.size()) {
            Inmueble inmueble2 = listaInmuebles.get(startIndex + 1);
            titulo2.setText(inmueble2.getTitulo());
            precio2.setText(Double.toString(inmueble2.getPrecioNoche()));
            media2.setText(Double.toString(inmueble2.getCalificacion()));
            foto2.setIcon(inmueble2.getFotos().get(0));
        }
        if (startIndex + 2 < listaInmuebles.size()) {
            Inmueble inmueble3 = listaInmuebles.get(startIndex + 2);
            titulo3.setText(inmueble3.getTitulo());
            precio3.setText(Double.toString(inmueble3.getPrecioNoche()));
            media3.setText(Double.toString(inmueble3.getCalificacion()));
            foto3.setIcon(inmueble3.getFotos().get(0));
        }
        if (startIndex + 3 < listaInmuebles.size()) {
            Inmueble inmueble4 = listaInmuebles.get(startIndex + 3);
            titulo4.setText(inmueble4.getTitulo());
            precio4.setText(Double.toString(inmueble4.getPrecioNoche()));
            media4.setText(Double.toString(inmueble4.getCalificacion()));
            foto4.setIcon(inmueble4.getFotos().get(0));
        }
    }//GEN-LAST:event_botonReseñaActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        if (pagAct < numPag){ pagAct++;}

        titulo1.setText("");
        precio1.setText("");
        media1.setText("");
        foto1.setIcon(null);

        titulo2.setText("");
        precio2.setText("");
        media2.setText("");
        foto2.setIcon(null);

        titulo3.setText("");
        precio3.setText("");
        media3.setText("");
        foto3.setIcon(null);

        titulo4.setText("");
        precio4.setText("");
        media4.setText("");
        foto4.setIcon(null);

        if (startIndex < listaInmuebles.size()) {
            Inmueble inmueble1 = listaInmuebles.get(pagAct*4);
            Image imagen1 = inmueble1.getFotos().get(0).getImage();
            titulo1.setText(inmueble1.getTitulo());
            precio1.setText(Double.toString(inmueble1.getPrecioNoche()));
            media1.setText(Double.toString(inmueble1.getCalificacion()));
            foto1.setIcon(inmueble1.getFotos().get(0)); // Asegúrate de manejar bien las fotos
        }
        if (startIndex + 1 < listaInmuebles.size()) {
            Inmueble inmueble2 = listaInmuebles.get(pagAct*4 + 1);
            titulo2.setText(inmueble2.getTitulo());
            precio2.setText(Double.toString(inmueble2.getPrecioNoche()));
            media2.setText(Double.toString(inmueble2.getCalificacion()));
            foto2.setIcon(inmueble2.getFotos().get(0));
        }
        if (startIndex + 2 < listaInmuebles.size()) {
            Inmueble inmueble3 = listaInmuebles.get(pagAct*4 + 2);
            titulo3.setText(inmueble3.getTitulo());
            precio3.setText(Double.toString(inmueble3.getPrecioNoche()));
            media3.setText(Double.toString(inmueble3.getCalificacion()));
            foto3.setIcon(inmueble3.getFotos().get(0));
        }
        if (startIndex + 3 < listaInmuebles.size()) {
            Inmueble inmueble4 = listaInmuebles.get(pagAct*4 + 3);
            titulo4.setText(inmueble4.getTitulo());
            precio4.setText(Double.toString(inmueble4.getPrecioNoche()));
            media4.setText(Double.toString(inmueble4.getCalificacion()));
            foto4.setIcon(inmueble4.getFotos().get(0));
        }
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorPrecioActionPerformed
        listaInmuebles = listaInmuebles2;
        botonReseña.setSelected(false);

        ArrayList<Inmueble> listaInmuebles = GestorInmueble.getInmueblesPorPrecio();

        titulo1.setText("");
        precio1.setText("");
        media1.setText("");
        foto1.setIcon(null);

        titulo2.setText("");
        precio2.setText("");
        media2.setText("");
        foto2.setIcon(null);

        titulo3.setText("");
        precio3.setText("");
        media3.setText("");
        foto3.setIcon(null);

        titulo4.setText("");
        precio4.setText("");
        media4.setText("");
        foto4.setIcon(null);

        if (startIndex < listaInmuebles.size()) {
            Inmueble inmueble1 = listaInmuebles.get(startIndex);
            Image imagen1 = inmueble1.getFotos().get(0).getImage();
            titulo1.setText(inmueble1.getTitulo());
            precio1.setText(Double.toString(inmueble1.getPrecioNoche()));
            media1.setText(Double.toString(inmueble1.getCalificacion()));
            foto1.setIcon(inmueble1.getFotos().get(0)); // Asegúrate de manejar bien las fotos
        }
        if (startIndex + 1 < listaInmuebles.size()) {
            Inmueble inmueble2 = listaInmuebles.get(startIndex + 1);
            titulo2.setText(inmueble2.getTitulo());
            precio2.setText(Double.toString(inmueble2.getPrecioNoche()));
            media2.setText(Double.toString(inmueble2.getCalificacion()));
            foto2.setIcon(inmueble2.getFotos().get(0));
        }
        if (startIndex + 2 < listaInmuebles.size()) {
            Inmueble inmueble3 = listaInmuebles.get(startIndex + 2);
            titulo3.setText(inmueble3.getTitulo());
            precio3.setText(Double.toString(inmueble3.getPrecioNoche()));
            media3.setText(Double.toString(inmueble3.getCalificacion()));
            foto3.setIcon(inmueble3.getFotos().get(0));
        }
        if (startIndex + 3 < listaInmuebles.size()) {
            Inmueble inmueble4 = listaInmuebles.get(startIndex + 3);
            titulo4.setText(inmueble4.getTitulo());
            precio4.setText(Double.toString(inmueble4.getPrecioNoche()));
            media4.setText(Double.toString(inmueble4.getCalificacion()));
            foto4.setIcon(inmueble4.getFotos().get(0));
        }
    }//GEN-LAST:event_botonPorPrecioActionPerformed
    ArrayList<Inmueble> listaInmuebles = anfitrion.getInmuebles();
    ArrayList<Inmueble> listaInmuebles2 = GestorInmueble.getInmuebles();
    int pagAct = 0; 
    int numPag = (int) Math.ceil(listaInmuebles.size()/4);
    int startIndex = pagAct*4;
    
    private ImageIcon imagen1;
    private ImageIcon imagen2;
    private ImageIcon imagen3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmpliarInmueble1;
    private javax.swing.JButton botonAtras;
    private javax.swing.JMenuItem botonPerfil;
    private javax.swing.JRadioButton botonPorPrecio;
    private javax.swing.JRadioButton botonReseña;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JMenuItem btnReservas;
    private javax.swing.JMenuItem btnReseñaModInm;
    private javax.swing.JMenuItem buscarGestionarInmuebles;
    private javax.swing.JCheckBox filtroApartamento;
    private javax.swing.JCheckBox filtroCasa;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel foto4;
    private javax.swing.JButton inmueble2;
    private javax.swing.JButton inmueble3;
    private javax.swing.JButton inmueble4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JLabel media1;
    private javax.swing.JLabel media2;
    private javax.swing.JLabel media3;
    private javax.swing.JLabel media4;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precio4;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
