

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabnb.frontend;

import java.awt.Image;
import java.awt.Point;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import javabnb.backend.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEJANDRO
 */
public class VentanaPago extends javax.swing.JFrame {

    private Persona persona;
    private ClienteParticular cliente;
    private double importe;
    private Inmueble inmueble;
    private ImageIcon image1;
    private LocalDate fechaEntrada;
    private LocalDate fechaSalida;
    /**
     * Creates new form MenuPrincipal
     * 
     * @param localizacion
     * @param persona
     */
    public VentanaPago( Point localizacion, Persona persona, Inmueble inmueble) {
        this.setLocation(localizacion);
        this.persona = persona;
        this.cliente = (ClienteParticular) persona;
        this.inmueble = inmueble;
        Image imagen1 = inmueble.getFotos().get(0).getImage(); // transform it 
        Image newimg1 = imagen1.getScaledInstance(250, 250,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        this.image1 = new ImageIcon(newimg1);  // transform it back
        
        initComponents();
        this.setVisible(true);
        if (persona instanceof ClienteParticular) {
            jMenu1.setText("Busqueda");
            buscarGestionarInmuebles.setText("Busqueda Inmuebles");
        }
        else {
            jMenu1.setText("Añadir");
            buscarGestionarInmuebles.setText("Añadir inmueble");
        }

        if (persona instanceof ClienteParticular) {
            jMenu2.setText("Reseñas");
            btnReseñaModInm.setText("Escribir Reseñas");
        }
        else {
            jMenu2.setText("Gestionar");
            btnReseñaModInm.setText("Modificar inmueble");
        }
        imgPrincipal.setIcon(image1);
        etiquetaTitulo.setText(inmueble.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        imgPrincipal = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCalcularPrecio = new javax.swing.JButton();
        etiquetaPrecio1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        fechaDeSalida = new javax.swing.JFormattedTextField();
        fechaDeEntrada = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buscarGestionarInmuebles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnReseñaModInm = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnReservas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        botonPerfil = new javax.swing.JMenuItem();

        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanelBusqueda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 70, -1, -1));

        jButton1.setText("jButton1");
        jPanelBusqueda.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 174, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaBnB");
        setMinimumSize(new java.awt.Dimension(900, 720));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fecha de entrada");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        imgPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoJavaBnB-PNGx2.png"))); // NOI18N
        getContentPane().add(imgPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        etiquetaTitulo.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaTitulo.setText("Titulo del inmueble");
        etiquetaTitulo.setMaximumSize(new java.awt.Dimension(600, 33));
        etiquetaTitulo.setMinimumSize(new java.awt.Dimension(600, 33));
        etiquetaTitulo.setPreferredSize(new java.awt.Dimension(600, 33));
        getContentPane().add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de salida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Precio Final");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btnCalcularPrecio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCalcularPrecio.setText("Calcular precio");
        btnCalcularPrecio.setPreferredSize(new java.awt.Dimension(300, 40));
        btnCalcularPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        etiquetaPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(etiquetaPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Precio Final");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.setPreferredSize(new java.awt.Dimension(300, 40));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        fechaDeSalida.setText("dd/mm/yyyy");
        fechaDeSalida.setToolTipText("");
        fechaDeSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaDeSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaDeSalidaFocusGained(evt);
            }
        });
        fechaDeSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDeSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(fechaDeSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        fechaDeEntrada.setText("dd/mm/yyyy");
        fechaDeEntrada.setToolTipText("");
        fechaDeEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaDeEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaDeEntradaFocusGained(evt);
            }
        });
        fechaDeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDeEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(fechaDeEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 73));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 73));

        jMenu1.setText("Busqueda");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu1.setMinimumSize(new java.awt.Dimension(120, 22));

        buscarGestionarInmuebles.setText("Buscar inmuebles");
        buscarGestionarInmuebles.setToolTipText("");
        buscarGestionarInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGestionarInmueblesActionPerformed(evt);
            }
        });
        jMenu1.add(buscarGestionarInmuebles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reseñas");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu2.setMinimumSize(new java.awt.Dimension(120, 22));

        btnReseñaModInm.setText("Escribir reseña");
        btnReseñaModInm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReseñaModInmActionPerformed(evt);
            }
        });
        jMenu2.add(btnReseñaModInm);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reservas");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu3.setMinimumSize(new java.awt.Dimension(120, 22));

        btnReservas.setText("Consultar reservas");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });
        jMenu3.add(btnReservas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Perfil");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu4.setMinimumSize(new java.awt.Dimension(120, 45));

        botonPerfil.setText("Modificar datos");
        botonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPerfilActionPerformed(evt);
            }
        });
        jMenu4.add(botonPerfil);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPerfilActionPerformed
        if (persona instanceof Anfitrion) {
            EditarAnfitrion editaranfitrion = new EditarAnfitrion(this.getLocation(),persona);
            this.dispose();
        }
        else {
            EditarCliente editarcliente = new EditarCliente(this.getLocation(),persona);
            this.dispose();
        }  
    }//GEN-LAST:event_botonPerfilActionPerformed

    private void buscarGestionarInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarGestionarInmueblesActionPerformed
        if (persona instanceof ClienteParticular) {
            //BuscarInmuebles busquedaInm = new BuscarInmuebles(this.getLocation(),persona);
            this.dispose();
        } else {
            CrearInmueble crearInmueble = new CrearInmueble(this.getLocation(),persona);
            this.dispose();
        }
    }//GEN-LAST:event_buscarGestionarInmueblesActionPerformed

    private void btnReseñaModInmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReseñaModInmActionPerformed
        if (persona instanceof Anfitrion) {
            ModificarInmueble modInmueble = new ModificarInmueble(this.getLocation(),persona);
            this.dispose();
        }
        else {
            AñadirReseña añadirReseña = new AñadirReseña(this.getLocation(),persona);
            this.dispose();
        }  
    }//GEN-LAST:event_btnReseñaModInmActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        ConsultarReservasCliente consultarReservas = new ConsultarReservasCliente(this.getLocation(),persona);
        this.dispose();
    }//GEN-LAST:event_btnReservasActionPerformed

    
    
    private void btnCalcularPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPrecioActionPerformed
         boolean fechaValida = true ;
         boolean fechaReservada = false;
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
        DateTimeFormatter formatogood = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDate fechaEntradaConvertida;
        LocalDate fechaSalidaConvertida;
        try {
            fechaEntradaConvertida = LocalDate.parse(fechaDeEntrada.getText(), formato);
            fechaSalidaConvertida = LocalDate.parse(fechaDeSalida.getText(), formato);
            long dias = ChronoUnit.DAYS.between(fechaEntradaConvertida, fechaSalidaConvertida);
            double precio = inmueble.getPrecioNoche() * dias;
            if (cliente.isVip()) {
                precio = 0.9 * precio;
            }
            if (fechaEntradaConvertida.isAfter(fechaSalidaConvertida)) {
                JOptionPane.showMessageDialog(this,"Fechas introducidas no validas","Error de fecha",JOptionPane.WARNING_MESSAGE);
                fechaValida = false;
            }
            if (!GestorInmueble.inmuebleDisponible(inmueble,fechaEntradaConvertida,fechaSalidaConvertida)) {
                JOptionPane.showMessageDialog(this,"Fechas introducidas ya reservadas","Error de fecha",JOptionPane.WARNING_MESSAGE);
                 fechaReservada = true;
            }
            this.fechaEntrada = fechaEntradaConvertida;
            this.fechaSalida = fechaSalidaConvertida;
            this.importe = precio;
            if (!fechaReservada && fechaValida){
            etiquetaPrecio1.setText(String.valueOf(Math.floor(precio * 100)/100) + "€");}
        } catch (DateTimeParseException e) {
            fechaDeSalida.setText("dd/mm/yyyy");
        
        }
    }//GEN-LAST:event_btnCalcularPrecioActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        Reserva reserva = new Reserva(inmueble, cliente.getTarjetaCredito(), cliente, fechaEntrada, fechaSalida);
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar factura");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                reserva.generarFactura(ruta);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,"Error al generar la factura","Error",JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                try {
                    Reserva.generarFactura(reserva);
                } catch (IOException ioe) {
                    JOptionPane.showMessageDialog(this,"Error al generar la factura, en carpeta de proyecto","Error",JOptionPane.ERROR_MESSAGE);
                    ioe.printStackTrace();
                
            }
        }
        MenuPrincipal menu = new MenuPrincipal(this.getLocation(),persona);
        this.dispose();
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void fechaDeSalidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaDeSalidaFocusGained
        if (fechaDeSalida.getText().equals("dd/mm/yyyy")) {
            fechaDeSalida.setText("");
        }
        fechaDeSalida.setToolTipText(null);
    }//GEN-LAST:event_fechaDeSalidaFocusGained

    private void fechaDeSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDeSalidaActionPerformed
    
    }//GEN-LAST:event_fechaDeSalidaActionPerformed

    private void fechaDeEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaDeEntradaFocusGained
        if (fechaDeEntrada.getText().equals("dd/mm/yyyy")) {
            fechaDeEntrada.setText("");
        }
        fechaDeEntrada.setToolTipText(null);
    }//GEN-LAST:event_fechaDeEntradaFocusGained

    private void fechaDeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDeEntradaActionPerformed

    }//GEN-LAST:event_fechaDeEntradaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this,"Estas seguro de cerrar","Cierre programa",JOptionPane.WARNING_MESSAGE);
        GestorInmueble.guardarDatosInmuebles();
        System.out.println("Guardando datos de inmuebles");
        GestorInmueble.guardarDatosPersonas();
        System.out.println("Guardando datos de personas");
        GestorInmueble.guardarDatosReservas();
        System.out.println("Guardando datos de reservas");
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem botonPerfil;
    private javax.swing.JButton btnCalcularPrecio;
    private javax.swing.JButton btnPagar;
    private javax.swing.JMenuItem btnReservas;
    private javax.swing.JMenuItem btnReseñaModInm;
    private javax.swing.JMenuItem buscarGestionarInmuebles;
    private javax.swing.JLabel etiquetaPrecio1;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JFormattedTextField fechaDeEntrada;
    private javax.swing.JFormattedTextField fechaDeSalida;
    private javax.swing.JLabel imgPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBusqueda;
    // End of variables declaration//GEN-END:variables
}
